// cms/src/components/Layout/LoadingIndicator.tsx
import { useContext } from "react";
// Context
import { LoadingContext } from "../../helper/Context";
// Assets
import logo from '../../assets/logoIcon.svg';

const LoadingIndicator: React.FC = () => {

    const { loadingState, setLoadingState } = useContext(LoadingContext);

    if(loadingState) {
        return (
            <div className="loadingIndCon">
                <img src={logo}/>
            </div>
        )
    }
    else return null;
}

export default LoadingIndicator;

// core/cms/src/components/general/LoadingIndicator.vue
<template>
    <img v-if="loadingState" class="loadingIndicator" src="@/assets/images/logoIcon.svg" alt="Logo Icon Spinning">
</template>

<script lang="ts">
export default {
    computed: {
        loadingState(): boolean {
            return this.$store.state.coreLoading.loadingState
        }
    }
}
</script>

<style lang="scss" scoped>

</style>
